//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1891
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Date :ObjectBase.ResourceBase<Date> {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Date() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibrary.Resources.Date", typeof(Date).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apr 的本地化字符串。
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aug 的本地化字符串。
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day(s) 的本地化字符串。
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM,yyyy 的本地化字符串。
        /// </summary>
        public static string dd_space_MMM_comma_yyyy {
            get {
                return ResourceManager.GetString("dd_space_MMM_comma_yyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM 的本地化字符串。
        /// </summary>
        public static string ddMMMml {
            get {
                return ResourceManager.GetString("ddMMMml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM HH:mm:ss 的本地化字符串。
        /// </summary>
        public static string ddMMMspwt {
            get {
                return ResourceManager.GetString("ddMMMspwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ddMMMyyyy 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyy {
            get {
                return ResourceManager.GetString("ddMMMyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd-MMM-yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyyd {
            get {
                return ResourceManager.GetString("ddMMMyyyyd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM,yyyy (ddd) 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyyddd {
            get {
                return ResourceManager.GetString("ddMMMyyyyddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM yyyy HH:mm 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyyHHmm {
            get {
                return ResourceManager.GetString("ddMMMyyyyHHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyyml {
            get {
                return ResourceManager.GetString("ddMMMyyyyml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ddMMMyyyy 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyyn {
            get {
                return ResourceManager.GetString("ddMMMyyyyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd/MMM/yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyys {
            get {
                return ResourceManager.GetString("ddMMMyyyys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyysp {
            get {
                return ResourceManager.GetString("ddMMMyyyysp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MMM yyyy HH:mm:ss 的本地化字符串。
        /// </summary>
        public static string ddMMMyyyyspwt {
            get {
                return ResourceManager.GetString("ddMMMyyyyspwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ddMMyyyy 的本地化字符串。
        /// </summary>
        public static string ddMMyyyy {
            get {
                return ResourceManager.GetString("ddMMyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd-MM-yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMyyyyd {
            get {
                return ResourceManager.GetString("ddMMyyyyd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ddMMyyyyn 的本地化字符串。
        /// </summary>
        public static string ddMMyyyyn {
            get {
                return ResourceManager.GetString("ddMMyyyyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd/MM/yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMyyyys {
            get {
                return ResourceManager.GetString("ddMMyyyys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd/MM/yyyy HH:mm 的本地化字符串。
        /// </summary>
        public static string ddMMyyyysHHmm {
            get {
                return ResourceManager.GetString("ddMMyyyysHHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dd MM yyyy 的本地化字符串。
        /// </summary>
        public static string ddMMyyyysp {
            get {
                return ResourceManager.GetString("ddMMyyyysp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dec 的本地化字符串。
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feb 的本地化字符串。
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fri 的本地化字符串。
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friday 的本地化字符串。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fri 的本地化字符串。
        /// </summary>
        public static string FriNum {
            get {
                return ResourceManager.GetString("FriNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jan 的本地化字符串。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jul 的本地化字符串。
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jun 的本地化字符串。
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mar 的本地化字符串。
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 May 的本地化字符串。
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMMdd 的本地化字符串。
        /// </summary>
        public static string MMMdd {
            get {
                return ResourceManager.GetString("MMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMM dd, yyyy 的本地化字符串。
        /// </summary>
        public static string MMMddyyyyspcm {
            get {
                return ResourceManager.GetString("MMMddyyyyspcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMMyyyy 的本地化字符串。
        /// </summary>
        public static string MMMyyyy {
            get {
                return ResourceManager.GetString("MMMyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mon 的本地化字符串。
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monday 的本地化字符串。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mon 的本地化字符串。
        /// </summary>
        public static string MonNum {
            get {
                return ResourceManager.GetString("MonNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month(s) 的本地化字符串。
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Night 的本地化字符串。
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Night(s) 的本地化字符串。
        /// </summary>
        public static string Nights {
            get {
                return ResourceManager.GetString("Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nov 的本地化字符串。
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oct 的本地化字符串。
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sat 的本地化字符串。
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sat 的本地化字符串。
        /// </summary>
        public static string SatNum {
            get {
                return ResourceManager.GetString("SatNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sat 的本地化字符串。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sep 的本地化字符串。
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun 的本地化字符串。
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun 的本地化字符串。
        /// </summary>
        public static string SunNum {
            get {
                return ResourceManager.GetString("SunNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thu 的本地化字符串。
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thu 的本地化字符串。
        /// </summary>
        public static string ThuNum {
            get {
                return ResourceManager.GetString("ThuNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thursday 的本地化字符串。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tue 的本地化字符串。
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tue 的本地化字符串。
        /// </summary>
        public static string TueNum {
            get {
                return ResourceManager.GetString("TueNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuesday 的本地化字符串。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wed 的本地化字符串。
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        public static string Webnesday {
            get {
                return ResourceManager.GetString("Webnesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wed 的本地化字符串。
        /// </summary>
        public static string WebNum {
            get {
                return ResourceManager.GetString("WebNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year(s) 的本地化字符串。
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyMMddHHmm 的本地化字符串。
        /// </summary>
        public static string yyMMddHHmm {
            get {
                return ResourceManager.GetString("yyMMddHHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yy/MM/dd HH:mm 的本地化字符串。
        /// </summary>
        public static string yyMMddHHmms {
            get {
                return ResourceManager.GetString("yyMMddHHmms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMddd 的本地化字符串。
        /// </summary>
        public static string yyyyMddd {
            get {
                return ResourceManager.GetString("yyyyMddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMdd 的本地化字符串。
        /// </summary>
        public static string yyyyMMdd {
            get {
                return ResourceManager.GetString("yyyyMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd 的本地化字符串。
        /// </summary>
        public static string yyyyMMddd {
            get {
                return ResourceManager.GetString("yyyyMMddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMMdd 的本地化字符串。
        /// </summary>
        public static string yyyyMMMdd {
            get {
                return ResourceManager.GetString("yyyyMMMdd", resourceCulture);
            }
        }
    }
}
