//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1882
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Errors() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibrary.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in all of the required fields. 的本地化字符串。
        /// </summary>
        public static string AlterRequiredFields {
            get {
                return ResourceManager.GetString("AlterRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Email already exists in the approval list. 的本地化字符串。
        /// </summary>
        public static string ApplyEmailExists {
            get {
                return ResourceManager.GetString("ApplyEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This License Number. already exists in the approval list. 的本地化字符串。
        /// </summary>
        public static string ApplyLicenseNoExists {
            get {
                return ResourceManager.GetString("ApplyLicenseNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change password failed! 的本地化字符串。
        /// </summary>
        public static string ChgPwdFailed {
            get {
                return ResourceManager.GetString("ChgPwdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Email has been used 的本地化字符串。
        /// </summary>
        public static string CompanyEmailExists {
            get {
                return ResourceManager.GetString("CompanyEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The License Number has been used 的本地化字符串。
        /// </summary>
        public static string CompanyLicenseNoExists {
            get {
                return ResourceManager.GetString("CompanyLicenseNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company({0}) has no been actived. 的本地化字符串。
        /// </summary>
        public static string CompanyNotActive {
            get {
                return ResourceManager.GetString("CompanyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company({0}) has been suspended. 的本地化字符串。
        /// </summary>
        public static string CompanySuspended {
            get {
                return ResourceManager.GetString("CompanySuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a office first. 的本地化字符串。
        /// </summary>
        public static string CompanyTypeError {
            get {
                return ResourceManager.GetString("CompanyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Agent Company Name 的本地化字符串。
        /// </summary>
        public static string EmptyAgentComName {
            get {
                return ResourceManager.GetString("EmptyAgentComName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Agent Contact Person 的本地化字符串。
        /// </summary>
        public static string EmptyAgentContactPer {
            get {
                return ResourceManager.GetString("EmptyAgentContactPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Agent Email Address 的本地化字符串。
        /// </summary>
        public static string EmptyAgentEmail {
            get {
                return ResourceManager.GetString("EmptyAgentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Agent Contact Number 的本地化字符串。
        /// </summary>
        public static string EmptyAgentPhone {
            get {
                return ResourceManager.GetString("EmptyAgentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Failure! 的本地化字符串。
        /// </summary>
        public static string ErrAddRecordMsg {
            get {
                return ResourceManager.GetString("ErrAddRecordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Amount 的本地化字符串。
        /// </summary>
        public static string ErrAmount {
            get {
                return ResourceManager.GetString("ErrAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Email 的本地化字符串。
        /// </summary>
        public static string ErrEmail {
            get {
                return ResourceManager.GetString("ErrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Number Format! 的本地化字符串。
        /// </summary>
        public static string ErrNum {
            get {
                return ResourceManager.GetString("ErrNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input correct city. 的本地化字符串。
        /// </summary>
        public static string ErrorCity {
            get {
                return ResourceManager.GetString("ErrorCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input correct country. 的本地化字符串。
        /// </summary>
        public static string ErrorCountry {
            get {
                return ResourceManager.GetString("ErrorCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter correct quantity for {0} 的本地化字符串。
        /// </summary>
        public static string ErrorQty {
            get {
                return ResourceManager.GetString("ErrorQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter traveller name(s) 的本地化字符串。
        /// </summary>
        public static string ErrorTraveller {
            get {
                return ResourceManager.GetString("ErrorTraveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error phone format. 的本地化字符串。
        /// </summary>
        public static string ErrPhone {
            get {
                return ResourceManager.GetString("ErrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a subject 的本地化字符串。
        /// </summary>
        public static string ErrSubject {
            get {
                return ResourceManager.GetString("ErrSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Failure! 的本地化字符串。
        /// </summary>
        public static string ErrUpdateRecordMsg {
            get {
                return ResourceManager.GetString("ErrUpdateRecordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The group code has existed! 的本地化字符串。
        /// </summary>
        public static string GroupCodeExist {
            get {
                return ResourceManager.GetString("GroupCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates Mandatory 的本地化字符串。
        /// </summary>
        public static string IndicatesMandatory {
            get {
                return ResourceManager.GetString("IndicatesMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the required information 的本地化字符串。
        /// </summary>
        public static string InputInfoRequired {
            get {
                return ResourceManager.GetString("InputInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid date format 的本地化字符串。
        /// </summary>
        public static string Invalid_date_format {
            get {
                return ResourceManager.GetString("Invalid_date_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please correct the information format. 的本地化字符串。
        /// </summary>
        public static string Invalid_inputformat {
            get {
                return ResourceManager.GetString("Invalid_inputformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Agent Email Address 的本地化字符串。
        /// </summary>
        public static string InvalidAgentEmail {
            get {
                return ResourceManager.GetString("InvalidAgentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid customer code. 的本地化字符串。
        /// </summary>
        public static string InvalidCustomerCode {
            get {
                return ResourceManager.GetString("InvalidCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Email format. 的本地化字符串。
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Fax Format. 的本地化字符串。
        /// </summary>
        public static string InvalidFax {
            get {
                return ResourceManager.GetString("InvalidFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid New Password! 的本地化字符串。
        /// </summary>
        public static string InvalidNewPwd {
            get {
                return ResourceManager.GetString("InvalidNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Old Password! 的本地化字符串。
        /// </summary>
        public static string InvalidOldPwd {
            get {
                return ResourceManager.GetString("InvalidOldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Phone format. 的本地化字符串。
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range (To.) should be greater than the Range (Fr.) 的本地化字符串。
        /// </summary>
        public static string InvalidPriceRange {
            get {
                return ResourceManager.GetString("InvalidPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price Range is conflict with the existing markup rule 的本地化字符串。
        /// </summary>
        public static string InvalidPriceRangeExist {
            get {
                return ResourceManager.GetString("InvalidPriceRangeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the fields 的本地化字符串。
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been disconnected as someone has signed in with your ID on another computer.&lt;br/&gt;&lt;br/&gt;Please note that if this was not intentional,someone may have stolen your password. 的本地化字符串。
        /// </summary>
        public static string KillOutString {
            get {
                return ResourceManager.GetString("KillOutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login incorrect - Please try again 的本地化字符串。
        /// </summary>
        public static string LoginErrString {
            get {
                return ResourceManager.GetString("LoginErrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your account is lock for 3 times password error. 的本地化字符串。
        /// </summary>
        public static string LoginIsLock {
            get {
                return ResourceManager.GetString("LoginIsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your account has been suspended. 的本地化字符串。
        /// </summary>
        public static string LoginSuspended {
            get {
                return ResourceManager.GetString("LoginSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-enter password does not match with the new password! 的本地化字符串。
        /// </summary>
        public static string NoMatchPwd {
            get {
                return ResourceManager.GetString("NoMatchPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no Accounts currently registered to this email address 的本地化字符串。
        /// </summary>
        public static string NoSchUserInADH {
            get {
                return ResourceManager.GetString("NoSchUserInADH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password length must be more than 6 Characters. 的本地化字符串。
        /// </summary>
        public static string PwdLength {
            get {
                return ResourceManager.GetString("PwdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Update Failed 的本地化字符串。
        /// </summary>
        public static string PwdUpdateFailed {
            get {
                return ResourceManager.GetString("PwdUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Field is Required! 的本地化字符串。
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password cannot be same as the old password! 的本地化字符串。
        /// </summary>
        public static string SameAsPwd {
            get {
                return ResourceManager.GetString("SameAsPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the correct email address. 的本地化字符串。
        /// </summary>
        public static string SendEmailRequired {
            get {
                return ResourceManager.GetString("SendEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The team code has existed! 的本地化字符串。
        /// </summary>
        public static string TeamCodeExist {
            get {
                return ResourceManager.GetString("TeamCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file was not uploaded because it does not have a .gif or .jpg extension. 的本地化字符串。
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your login account is currently in used.Please try again later! 的本地化字符串。
        /// </summary>
        public static string UserInUsed {
            get {
                return ResourceManager.GetString("UserInUsed", resourceCulture);
            }
        }
    }
}
